CREATE TABLE IF NOT EXISTS BICM014 (
    COLLECTOR_NAME VARCHAR(40) COMMENT '수집기 이름',
    COLLECTOR_ADDR VARCHAR(15) COMMENT '수집기 IP 주소',
    COLLECTOR_OFFSET_STRING VARCHAR(23) COMMENT '수집기 오프셋 문자열',
    SNO BIGINT COMMENT '일련번호',
    SIDO VARCHAR(50) COMMENT '시도',
    SGU VARCHAR(50) COMMENT '시군구',
    X VARCHAR(20) COMMENT 'X좌표',
    Y VARCHAR(20) COMMENT 'Y좌표',
    CREATEDATE DATETIME COMMENT '생성일시',
    PRIMARY KEY (SNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그 테이블'; 