CREATE TABLE IF NOT EXISTS BICM013 (
    COLLECTOR_NAME VARCHAR(40) COMMENT '수집기 이름',
    COLLECTOR_ADDR VARCHAR(15) COMMENT '수집기 IP 주소',
    COLLECTOR_OFFSET_STRING VARCHAR(23) COMMENT '수집기 오프셋 문자열',
    SNO BIGINT COMMENT '일련번호',
    BRCD VARCHAR(5) COMMENT '지점코드',
    COLCD VARCHAR(10) COMMENT '색상코드',
    COLCDNM VARCHAR(100) COMMENT '색상코드명',
    RGBCOLCD VARCHAR(10) COMMENT 'RGB색상코드',
    REGDT DATETIME COMMENT '등록일시',
    REGEMPID VARCHAR(16) COMMENT '등록자ID',
    UPDDT DATETIME COMMENT '수정일시',
    UPDEMPID VARCHAR(16) COMMENT '수정자ID',
    PRIMARY KEY (SNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그 테이블'; 