CREATE TABLE IF NOT EXISTS BICM011 (
    COLLECTOR_NAME VARCHAR(40) COMMENT '수집기 이름',
    COLLECTOR_ADDR VARCHAR(15) COMMENT '수집기 IP 주소',
    COLLECTOR_OFFSET_STRING VARCHAR(23) COMMENT '수집기 오프셋 문자열',
    SNO BIGINT COMMENT '일련번호',
    GBNCD VARCHAR(10) COMMENT '구분 코드',
    CODE VARCHAR(10) COMMENT '코드',
    CODNM VARCHAR(50) COMMENT '코드명',
    USEYN CHAR(1) COMMENT '사용여부',
    MEMO VARCHAR(400) COMMENT '메모',
    ADDINFO VARCHAR(200) COMMENT '추가정보',
    ADDINFO1 VARCHAR(200) COMMENT '추가정보1',
    SORTORD SMALLINT COMMENT '정렬순서',
    REGDT DATETIME COMMENT '등록일시',
    REGEMPID VARCHAR(16) COMMENT '등록자ID',
    UPDDT DATETIME COMMENT '수정일시',
    UPDEMPID VARCHAR(16) COMMENT '수정자ID',
    PRIMARY KEY (SNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그 테이블'; 