CREATE TABLE IF NOT EXISTS BIGR010 (
    COLLECTOR_NAME VARCHAR(40) COMMENT '수집기 이름',
    COLLECTOR_ADDR VARCHAR(15) COMMENT '수집기 IP 주소',
    COLLECTOR_OFFSET_STRING VARCHAR(23) COMMENT '수집기 오프셋 문자열',
    SNO BIGINT COMMENT '일련번호',
    EMPCD VARCHAR(20) COMMENT '사원코드',
    GBNCD VARCHAR(10) COMMENT '구분코드',
    GRTCD VARCHAR(10) COMMENT '권한코드',
    REFCD VARCHAR(10) COMMENT '참조코드',
    MCODE VARCHAR(10) COMMENT '메뉴코드',
    PROCD VARCHAR(20) COMMENT '프로그램코드',
    VIEWYN CHAR(1) COMMENT '조회여부',
    PRINTYN CHAR(1) COMMENT '출력여부',
    CREATEDATE DATETIME COMMENT '생성일시',
    PRIMARY KEY (SNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그 테이블'; 