CREATE TABLE IF NOT EXISTS BION050 (
    COLLECTOR_NAME VARCHAR(40) COMMENT '수집기 이름',
    COLLECTOR_ADDR VARCHAR(15) COMMENT '수집기 IP 주소',
    COLLECTOR_OFFSET_STRING VARCHAR(23) COMMENT '수집기 오프셋 문자열',
    SNO BIGINT COMMENT '일련번호',
    MAINGU VARCHAR(10) COMMENT '메인구분',
    SUBGU VARCHAR(10) COMMENT '서브구분',
    GUBUN VARCHAR(10) COMMENT '구분',
    SALEDT VARCHAR(8) COMMENT '판매일자',
    PLNAMT BIGINT COMMENT '계획금액',
    SAMT BIGINT COMMENT '판매금액',
    LYSAMT BIGINT COMMENT '전년판매금액',
    CREATEDATE DATETIME COMMENT '생성일시',
    PRIMARY KEY (SNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그 테이블'; 