CREATE TABLE IF NOT EXISTS BION060 (
    COLLECTOR_NAME VARCHAR(40) COMMENT '수집기 이름',
    COLLECTOR_ADDR VARCHAR(15) COMMENT '수집기 IP 주소',
    COLLECTOR_OFFSET_STRING VARCHAR(23) COMMENT '수집기 오프셋 문자열',
    SNO BIGINT COMMENT '일련번호',
    SUCD VARCHAR(5) COMMENT '공급사코드',
    BRCD VARCHAR(5) COMMENT '지점코드',
    VDCD VARCHAR(10) COMMENT '벤더코드',
    SALEDT VARCHAR(8) COMMENT '판매일자',
    SILAMT BIGINT COMMENT '실적금액',
    CREATEDATE DATETIME COMMENT '생성일시',
    PRIMARY KEY (SNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그 테이블'; 