CREATE TABLE IF NOT EXISTS BISL010 (
    COLLECTOR_NAME VARCHAR(40) COMMENT '수집기 이름',
    COLLECTOR_ADDR VARCHAR(15) COMMENT '수집기 IP 주소',
    COLLECTOR_OFFSET_STRING VARCHAR(23) COMMENT '수집기 오프셋 문자열',
    SNO BIGINT COMMENT '일련번호',
    COMCD VARCHAR(5) COMMENT '회사코드',
    SUCD VARCHAR(5) COMMENT '공급사코드',
    BRCD VARCHAR(5) COMMENT '지점코드',
    YYYYMMDD VARCHAR(8) COMMENT '년월일',
    COMNM VARCHAR(50) COMMENT '회사명',
    SUNM VARCHAR(30) COMMENT '공급사명',
    BRNM VARCHAR(30) COMMENT '지점명',
    BRSNM VARCHAR(20) COMMENT '지점단축명',
    AMT BIGINT COMMENT '금액',
    CREATEDATE DATETIME COMMENT '생성일시',
    PRIMARY KEY (SNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그 테이블'; 