CREATE TABLE IF NOT EXISTS BIWE051 (
    COLLECTOR_NAME VARCHAR(40) COMMENT '수집기 이름',
    COLLECTOR_ADDR VARCHAR(15) COMMENT '수집기 IP 주소',
    COLLECTOR_OFFSET_STRING VARCHAR(23) COMMENT '수집기 오프셋 문자열',
    COMCD VARCHAR(5) COMMENT '회사코드',
    SUCD VARCHAR(5) COMMENT '공급사코드',
    BRCD VARCHAR(5) COMMENT '지점코드',
    YYYY VARCHAR(4) COMMENT '연도',
    MM VARCHAR(2) COMMENT '월',
    WEEK VARCHAR(2) COMMENT '주',
    FROM_SALEDT VARCHAR(8) COMMENT '시작판매일자',
    TO_SALEDT VARCHAR(8) COMMENT '종료판매일자',
    SNO BIGINT COMMENT '일련번호',
    PROGRESS VARCHAR(2000) COMMENT '진행상황',
    PLAN VARCHAR(2000) COMMENT '계획',
    CREATEDATE DATETIME COMMENT '생성일시',
    TEMP_SAVE VARCHAR(5) COMMENT '임시저장',
    PRIMARY KEY (SNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그 테이블'; 